---
title: "Atividade 04"
output: html_document
---


Vocês deverão refazer a Atividade 2. Para tanto, sigam as instruções a seguir.

Leiam com atenção os textos:

* [Dicas de escrita (no moodle)](http://www.ggte.unicamp.br/eam/mod/resource/view.php?id=136829).

* [The art of writing science](https://dx.doi.org/10.1002%2Fpro.514).


Façam buscas, utilizando o [Google Scholar](https://scholar.google.com), dos métodos estatísticos utilizados na Atividade 2. Como os resultados costumam ser apresentados em artigos científicos? 

Cada grupo (os mesmos da Atividade 2) deverá entregar:

* Resumo escrito à mão do texto [The art of writing science](https://dx.doi.org/10.1002%2Fpro.514). 
**Cada membro do grupo deverá produzir o seu próprio resumo**.
* 5 exemplos de artigos científicos em que os métodos estatísticos utilizados na Atividade 2 foram utilizados. Envie um arquivo compactado (`.zip`), via Moodle, contendo os arquivos `.pdf` dos artigos, com os **trechos dos métodos utilizados grifados**.
* Atividade 2 refeita, escrita à mão. Caso haja algum gráfico, o mesmo deve apenas ser listado no texto.


Para acessar alguns dos livros digitais fora da Unicamp, você poderá precisar do VPN. Veja instruções de instalação [aqui](https://www.ccuec.unicamp.br/ccuec/servicos/acesso_remoto_vpn).

